# Generated by Django 5.2 on 2025-05-17 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathgame', '0003_subboard_alter_path_board'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='pathgame.board')),
            ],
            options={
                'unique_together': {('board', 'x', 'y')},
            },
        ),
    ]
