# Generated by Django 5.2 on 2025-05-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathgame', '0004_boardpoint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardpoint',
            old_name='x',
            new_name='col',
        ),
        migrations.RenameField(
            model_name='boardpoint',
            old_name='y',
            new_name='row',
        ),
        migrations.AlterUniqueTogether(
            name='boardpoint',
            unique_together={('board', 'row', 'col')},
        ),
        migrations.AddField(
            model_name='boardpoint',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
