# Generated by Django 5.2 on 2025-05-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathgame', '0005_rename_x_boardpoint_col_rename_y_boardpoint_row_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardpoint',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
