# Generated by Django 5.2 on 2025-05-19 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathgame', '0006_alter_boardpoint_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pathpoint',
            old_name='x',
            new_name='col',
        ),
        migrations.RenameField(
            model_name='pathpoint',
            old_name='y',
            new_name='row',
        ),
    ]
