# Generated by Django 5.2 on 2025-05-19 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathgame', '0007_rename_x_pathpoint_col_rename_y_pathpoint_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths', to='pathgame.subboard'),
        ),
    ]
